-- Safe to re-run: uses IF NOT EXISTS / OR REPLACE / DROP POLICY IF EXISTS
-- Run in Supabase SQL Editor (Dashboard → SQL → New query)

create table if not exists public.rider_payment_data (
  id bigint generated by default as identity primary key,
  client_name text,
  type text,
  week text,
  month text,
  rider_id text,
  rider_name text,
  city text,
  orders numeric,
  payout_1 numeric,
  payout_2 numeric,
  margin numeric,
  gross_payout numeric,
  tds numeric,
  cod_deduction numeric,
  cod_recovery numeric,
  client_deductions numeric,
  sd numeric,
  damage numeric,
  insurance numeric,
  fleet numeric,
  traffic numeric,
  on_hold numeric,
  ev_rent numeric,
  final_net_payout numeric,
  payment_status text,
  payment_date text,
  utr_number text,
  remarks text,
  acc_no text,
  ifsc_code text,
  pan_number text,
  vehicle_number text,
  margin_pct numeric,
  margin_amount numeric,
  region text,
  created_at timestamptz not null default now()
);

create index if not exists rider_payment_data_rider_id_idx on public.rider_payment_data (rider_id);
create index if not exists rider_payment_data_month_idx on public.rider_payment_data (month);
create index if not exists rider_payment_data_month_id_idx on public.rider_payment_data (month, id);

create table if not exists public.manual_collation_data (
  id bigint generated by default as identity primary key,
  month text,
  transaction_date text,
  value_date text,
  transaction_particulars text,
  reference_number text,
  withdrawals numeric,
  deposits numeric,
  purpose text,
  rider_name text,
  city text,
  rider_id text,
  vehicle_number text,
  remarks text,
  created_at timestamptz not null default now()
);

create index if not exists manual_collation_data_rider_id_idx on public.manual_collation_data (rider_id);
create index if not exists manual_collation_data_month_idx on public.manual_collation_data (month);
create index if not exists manual_collation_data_month_id_idx on public.manual_collation_data (month, id);

alter table public.rider_payment_data enable row level security;
alter table public.manual_collation_data enable row level security;

drop policy if exists "Allow anon read rider_payment_data" on public.rider_payment_data;
create policy "Allow anon read rider_payment_data"
  on public.rider_payment_data for select to anon using (true);

drop policy if exists "Allow anon insert rider_payment_data" on public.rider_payment_data;
create policy "Allow anon insert rider_payment_data"
  on public.rider_payment_data for insert to anon with check (true);

drop policy if exists "Allow anon delete rider_payment_data" on public.rider_payment_data;
create policy "Allow anon delete rider_payment_data"
  on public.rider_payment_data for delete to anon using (true);

drop policy if exists "Allow anon read manual_collation_data" on public.manual_collation_data;
create policy "Allow anon read manual_collation_data"
  on public.manual_collation_data for select to anon using (true);

drop policy if exists "Allow anon insert manual_collation_data" on public.manual_collation_data;
create policy "Allow anon insert manual_collation_data"
  on public.manual_collation_data for insert to anon with check (true);

drop policy if exists "Allow anon delete manual_collation_data" on public.manual_collation_data;
create policy "Allow anon delete manual_collation_data"
  on public.manual_collation_data for delete to anon using (true);

-- Fast distinct month lists for Rider Payment Upload reset dropdowns
create or replace function public.distinct_rider_payment_months()
returns table (month text)
language sql
stable
security definer
set search_path = public
as $$
  select m.month
  from public.rider_payment_data m
  where m.month is not null and m.month <> ''
  group by m.month
  order by m.month desc;
$$;

create or replace function public.distinct_manual_collation_months()
returns table (month text)
language sql
stable
security definer
set search_path = public
as $$
  select m.month
  from public.manual_collation_data m
  where m.month is not null and m.month <> ''
  group by m.month
  order by m.month desc;
$$;

grant execute on function public.distinct_rider_payment_months() to anon, authenticated;
grant execute on function public.distinct_manual_collation_months() to anon, authenticated;

-- Rental pending amount (weekly rent / SD reconciliation upload)
create table if not exists public.rental_pending_data (
  id bigint generated by default as identity primary key,
  month text,
  deployed_date text,
  db_current_status text,
  vehicle_status text,
  current_status text,
  client_name text,
  contact_no text,
  rider_name text,
  ev91_rider_id text,
  rider_id text,
  vehicle_number text,
  city text,
  week_start_date text,
  week_end_date text,
  number_of_days_with_rider numeric,
  area_location text,
  rent_per_week numeric,
  source_name text,
  -- Week number in Excel changes (Deficit Week 22/34, WK 23/35 EV Rent, etc.)
  deficit_amount_week_22 numeric,
  wk_23_ev_rent numeric,
  total_rent_amount numeric,
  payout_deduction_week_23 numeric,
  total_sd_amount numeric,
  pending_amount numeric,
  manual_payment_collection numeric,
  -- Stores "Actual pending for Week" (and legacy "… After SD")
  actual_pending_for_week_after_sd numeric,
  payment_collected_date text,
  inactive_days numeric,
  eff_inff text,
  current_week_orders numeric,
  remarks text,
  remarks_by_fr text,
  created_at timestamptz not null default now()
);

create index if not exists rental_pending_data_rider_id_idx on public.rental_pending_data (rider_id);
create index if not exists rental_pending_data_ev91_rider_id_idx on public.rental_pending_data (ev91_rider_id);
create index if not exists rental_pending_data_month_idx on public.rental_pending_data (month);
create index if not exists rental_pending_data_month_id_idx on public.rental_pending_data (month, id);
create index if not exists rental_pending_data_vehicle_number_idx on public.rental_pending_data (vehicle_number);

alter table public.rental_pending_data enable row level security;

drop policy if exists "Allow anon read rental_pending_data" on public.rental_pending_data;
create policy "Allow anon read rental_pending_data"
  on public.rental_pending_data for select to anon using (true);

drop policy if exists "Allow anon insert rental_pending_data" on public.rental_pending_data;
create policy "Allow anon insert rental_pending_data"
  on public.rental_pending_data for insert to anon with check (true);

drop policy if exists "Allow anon delete rental_pending_data" on public.rental_pending_data;
create policy "Allow anon delete rental_pending_data"
  on public.rental_pending_data for delete to anon using (true);

create or replace function public.distinct_rental_pending_months()
returns table (month text)
language sql
stable
security definer
set search_path = public
as $$
  select m.month
  from public.rental_pending_data m
  where m.month is not null and m.month <> ''
  group by m.month
  order by m.month desc;
$$;

grant execute on function public.distinct_rental_pending_months() to anon, authenticated;

create or replace function public.reset_upload_table_batch(
  p_table text,
  p_month text default null,
  p_limit integer default 1500
)
returns integer
language plpgsql
security definer
set search_path = public
set statement_timeout = '30s'
as $$
declare
  tbl text;
  lim integer;
  n integer := 0;
  month_label text;
begin
  tbl := case p_table
    when 'rider_payment_data' then 'rider_payment_data'
    when 'manual_collation_data' then 'manual_collation_data'
    when 'rental_pending_data' then 'rental_pending_data'
    when 'ev91_sd_data' then 'ev91_sd_data'
    else null
  end;
  if tbl is null then
    raise exception 'unsupported table: %', p_table;
  end if;

  lim := greatest(50, least(coalesce(p_limit, 1500), 3000));
  month_label := nullif(btrim(coalesce(p_month, '')), '');

  if month_label is null or tbl = 'ev91_sd_data' then
    execute format(
      'delete from public.%I where id in (select id from public.%I order by id limit %s)',
      tbl, tbl, lim
    );
  else
    execute format(
      'delete from public.%I where id in (select id from public.%I where month = $1 order by id limit %s)',
      tbl, tbl, lim
    ) using month_label;
  end if;

  get diagnostics n = row_count;
  return n;
end;
$$;

grant execute on function public.reset_upload_table_batch(text, text, integer) to anon, authenticated;
