-- Vehicle service done log (Service Schedule page)
-- Safe to re-run. Run in Supabase SQL Editor.

create table if not exists public.vehicle_service_log (
  id bigint generated by default as identity primary key,
  vehicle_number text not null,
  vehicle_key text not null,
  service_date date not null default (current_date),
  service_status text not null default 'done',
  city text,
  client_name text,
  rider_id text,
  rider_name text,
  ev91_rider_id text,
  total_km numeric,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists vehicle_service_log_vehicle_key_idx
  on public.vehicle_service_log (vehicle_key);

create index if not exists vehicle_service_log_service_date_idx
  on public.vehicle_service_log (service_date);

create index if not exists vehicle_service_log_vehicle_number_idx
  on public.vehicle_service_log (vehicle_number);

alter table public.vehicle_service_log enable row level security;

drop policy if exists "Allow anon read vehicle_service_log" on public.vehicle_service_log;
create policy "Allow anon read vehicle_service_log"
  on public.vehicle_service_log for select to anon using (true);

drop policy if exists "Allow anon insert vehicle_service_log" on public.vehicle_service_log;
create policy "Allow anon insert vehicle_service_log"
  on public.vehicle_service_log for insert to anon with check (true);

drop policy if exists "Allow anon delete vehicle_service_log" on public.vehicle_service_log;
create policy "Allow anon delete vehicle_service_log"
  on public.vehicle_service_log for delete to anon using (true);
