-- Run once in Supabase SQL Editor (Dashboard → SQL → New query)
create table if not exists public.client_targets (
  id bigint generated by default as identity primary key,
  week_key text not null,
  city text not null default '',
  client text not null,
  type text not null default '' check (type in ('EV', 'NON-EV')),
  target numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (week_key, city, client, type)
);

create index if not exists client_targets_week_key_idx on public.client_targets (week_key);

alter table public.client_targets enable row level security;

create policy "Allow anon read client_targets"
  on public.client_targets for select to anon using (true);

create policy "Allow anon insert client_targets"
  on public.client_targets for insert to anon with check (true);

create policy "Allow anon update client_targets"
  on public.client_targets for update to anon using (true) with check (true);

create policy "Allow anon delete client_targets"
  on public.client_targets for delete to anon using (true);
