-- Safe to re-run: uses IF NOT EXISTS / DROP POLICY IF EXISTS
-- Run in Supabase SQL Editor (Dashboard → SQL → New query)
-- Separate from rider_metrics — for manual order tracking uploads.
-- Unique key: Date + WorkerCode + Client + delivered
-- (same rider can have multiple order counts on the same day, e.g. 11 and 5)

create table if not exists public.order_upload_data (
  id bigint generated by default as identity primary key,
  client text,
  date_record text,
  worker_code text,
  delivered numeric,
  city text,
  type1 text,
  month text,
  created_at timestamptz not null default now()
);

create index if not exists order_upload_data_worker_code_idx on public.order_upload_data (worker_code);
create index if not exists order_upload_data_date_record_idx on public.order_upload_data (date_record);
create index if not exists order_upload_data_month_idx on public.order_upload_data (month);
create index if not exists order_upload_data_client_idx on public.order_upload_data (client);
create index if not exists order_upload_data_type1_idx on public.order_upload_data (type1);

-- Remove older exact duplicates (same date + rider + client + delivered).
delete from public.order_upload_data a
using public.order_upload_data b
where a.worker_code is not null
  and a.date_record is not null
  and trim(a.worker_code) <> ''
  and trim(a.date_record) <> ''
  and a.worker_code = b.worker_code
  and a.date_record = b.date_record
  and coalesce(a.client, '') = coalesce(b.client, '')
  and coalesce(a.delivered, 0) = coalesce(b.delivered, 0)
  and a.id < b.id;

drop index if exists order_upload_data_worker_date_uidx;
drop index if exists order_upload_data_worker_date_client_uidx;
create unique index if not exists order_upload_data_worker_date_client_delivered_uidx
  on public.order_upload_data (worker_code, date_record, client, delivered);

alter table public.order_upload_data enable row level security;

drop policy if exists "Allow anon read order_upload_data" on public.order_upload_data;
create policy "Allow anon read order_upload_data"
  on public.order_upload_data for select to anon using (true);

drop policy if exists "Allow anon insert order_upload_data" on public.order_upload_data;
create policy "Allow anon insert order_upload_data"
  on public.order_upload_data for insert to anon with check (true);

drop policy if exists "Allow anon update order_upload_data" on public.order_upload_data;
create policy "Allow anon update order_upload_data"
  on public.order_upload_data for update to anon using (true) with check (true);

drop policy if exists "Allow anon delete order_upload_data" on public.order_upload_data;
create policy "Allow anon delete order_upload_data"
  on public.order_upload_data for delete to anon using (true);

create or replace function public.distinct_order_upload_months()
returns table (month text)
language sql
stable
as $$
  select distinct m.month
  from public.order_upload_data m
  where m.month is not null and trim(m.month) <> ''
  order by 1 desc;
$$;

grant execute on function public.distinct_order_upload_months() to anon;
grant execute on function public.distinct_order_upload_months() to authenticated;
