-- EV91 SD upload (Payment Upload → EV91 SD → SD & EV Rent page)
-- Safe to re-run. Run in Supabase SQL Editor.

create table if not exists public.ev91_sd_data (
  id bigint generated by default as identity primary key,
  public_rider_id text,
  city text,
  client_name text,
  client_rider_id text,
  total_sd numeric,
  pending_sd numeric,
  fixed_deposit numeric,
  created_at timestamptz not null default now()
);

create index if not exists ev91_sd_data_public_rider_id_idx on public.ev91_sd_data (public_rider_id);
create index if not exists ev91_sd_data_client_rider_id_idx on public.ev91_sd_data (client_rider_id);

alter table public.ev91_sd_data enable row level security;

drop policy if exists "Allow anon read ev91_sd_data" on public.ev91_sd_data;
create policy "Allow anon read ev91_sd_data"
  on public.ev91_sd_data for select to anon using (true);

drop policy if exists "Allow anon insert ev91_sd_data" on public.ev91_sd_data;
create policy "Allow anon insert ev91_sd_data"
  on public.ev91_sd_data for insert to anon with check (true);

drop policy if exists "Allow anon delete ev91_sd_data" on public.ev91_sd_data;
create policy "Allow anon delete ev91_sd_data"
  on public.ev91_sd_data for delete to anon using (true);
