-- Vehicle master upload for Error Finder V Mismatch checks.
-- Safe to re-run: uses IF NOT EXISTS / DROP POLICY IF EXISTS

create table if not exists public.vehicle_master (
  id bigint generated by default as identity primary key,
  master_date text not null,
  month text,
  vehicle_number text,
  chassis_number text,
  engine_motor_number text,
  created_at timestamptz not null default now()
);

create index if not exists vehicle_master_master_date_idx on public.vehicle_master (master_date);
create index if not exists vehicle_master_vehicle_number_idx on public.vehicle_master (vehicle_number);
create index if not exists vehicle_master_month_idx on public.vehicle_master (month);

alter table public.vehicle_master enable row level security;

drop policy if exists "Allow anon read vehicle_master" on public.vehicle_master;
create policy "Allow anon read vehicle_master"
  on public.vehicle_master for select to anon using (true);

drop policy if exists "Allow anon insert vehicle_master" on public.vehicle_master;
create policy "Allow anon insert vehicle_master"
  on public.vehicle_master for insert to anon with check (true);

drop policy if exists "Allow anon delete vehicle_master" on public.vehicle_master;
create policy "Allow anon delete vehicle_master"
  on public.vehicle_master for delete to anon using (true);

create or replace function public.distinct_vehicle_master_dates()
returns table (master_date text)
language sql
stable
security definer
set search_path = public
as $$
  select distinct btrim(master_date) as master_date
  from public.vehicle_master
  where master_date is not null and btrim(master_date) <> ''
  order by 1 desc;
$$;

grant execute on function public.distinct_vehicle_master_dates() to anon, authenticated;
